<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BusinessDataLogicAppservice\**" />
    <Compile Remove="DataLogicDataService\**" />
    <EmbeddedResource Remove="BusinessDataLogicAppservice\**" />
    <EmbeddedResource Remove="DataLogicDataService\**" />
    <None Remove="BusinessDataLogicAppservice\**" />
    <None Remove="DataLogicDataService\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessDataLogicLyr\BusinessDataLogicLyr.csproj" />
    <ProjectReference Include="..\DataLgcLyr\DataLgcLyr.csproj" />
    <ProjectReference Include="..\DataMdlLyr\DataMdlLyr.csproj" />
  </ItemGroup>

</Project>
