<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BusinessDataLogicAppservice\**" />
    <Compile Remove="DataLogicDataService\**" />
    <Compile Remove="GradeCalculationBusinessDataLogic\**" />
    <Compile Remove="GradeCalculationDataLogicLayer\**" />
    <Compile Remove="GradeCalculationDataModel\**" />
    <Compile Remove="GradeDataModel\**" />
    <EmbeddedResource Remove="BusinessDataLogicAppservice\**" />
    <EmbeddedResource Remove="DataLogicDataService\**" />
    <EmbeddedResource Remove="GradeCalculationBusinessDataLogic\**" />
    <EmbeddedResource Remove="GradeCalculationDataLogicLayer\**" />
    <EmbeddedResource Remove="GradeCalculationDataModel\**" />
    <EmbeddedResource Remove="GradeDataModel\**" />
    <None Remove="BusinessDataLogicAppservice\**" />
    <None Remove="DataLogicDataService\**" />
    <None Remove="GradeCalculationBusinessDataLogic\**" />
    <None Remove="GradeCalculationDataLogicLayer\**" />
    <None Remove="GradeCalculationDataModel\**" />
    <None Remove="GradeDataModel\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="GradeCalculationBusinessDataLogic\GradeCalculationBusinessDataLogic.csproj" />
    <ProjectReference Include="GradeDataModel\GradeDataModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="GradeBackup\" />
  </ItemGroup>

</Project>
